// central types used across the UI and API layer
export type User = {
  id: number | string;
  name: string;
  username?: string;
  avatar?: string;
  author_handle?: string;
  is_trusted?: boolean;
  is_partner?: boolean;
  verified_badge?: boolean;
  business_slug?: string;
  business_name?: string;
};

export type APIComment = {
  comment_id: number;
  post_id: number;
  user_id: number;
  comment_content: string;
  location?: string | null;
  comment_at: string;
  is_author: number;
  is_first_comment: number;
  author_name: string;
  author_pic?: string;
  author_handle?: string;
  author_is_trusted?: boolean;
  author_is_partner?: boolean;
  is_partner?: boolean;
  verified_badge?: boolean;
  likes_count: number;
  author_liked?: boolean;
  followers_count?: number;
  posts_count?: number;
  liked_by_user?: boolean;
  parent_id?: number | null;
  metadata?: any;
};

export type Post = {
  id: number | string;
  apiId?: number | string;
  social_post_id?: number | string;
  post_public_id?: number | string;
  src?: string;
  isVideo?: boolean;
  isImage?: boolean;
  caption?: string;
  note_caption?: string;
  user: User;
  author_handle?: string;
  author_name?: string;
  author_pic?: string;
  liked: boolean;
  liked_by_me?: boolean;
  liked_by_user?: boolean;
  is_following?: boolean;
  likeCount: number;
  likes_count?: number;
  likesCount?: number;
  comment_count?: number;
  commentCount?: number;
  total_comments?: number;
  comments_count?: number;
  coverType?: string;
  noteConfig?: any;
  rawCreatedAt?: string;
  privacy?: string;
  subtitle?: string;
  allMedia?: { url: string; id: any }[];
  location?: string | null;
  category?: string;
  isPinned?: boolean;
  pinnedAt?: string;
  status?: string;
  thumbnail?: string;
  mediaType?: string;
  final_video_url?: string;
  original_video_url?: string;
  original_audio_url?: string;
  is_product_linked?: boolean;
  linked_product?: {
    product_id: number | string;
    title: string;
    slug?: string;
    product_slug?: string;
    business_slug?: string;
    price: number | string;
    image_url?: string;
    first_image?: string;
    total_sold?: number;
    total_quantity?: number;
    return_shipping_subsidy?: boolean;
    seven_day_no_reason_return?: boolean;
    promotions_data?: any;
    sale_discount_data?: any;
    verified_badge?: boolean;
    trusted_partner?: boolean;
    business_name?: string;
    total_likes?: number;
    followers_count?: number;
  } | null;
  business_slug?: string;
  business_name?: string;
  verified_badge?: boolean;
  author_is_partner?: boolean;
};
