export interface PostModalContext {
  // Mobile Reels View
  isMobileReels?: boolean;
  videoPortHeight: string | number;
  showCommentsSheet: boolean;
  setShowCommentsSheet: (val: boolean) => void;
  currentReelIndex: number;
  fastScrollVelocityRef: React.MutableRefObject<boolean>;
  dismissSwipeGuide: () => void;
  reelsList: any[];
  setCurrentReelIndex: React.Dispatch<React.SetStateAction<number>>;
  lastScrollTimeRef: React.MutableRefObject<number>;
  handleVideoRegister: (el: HTMLVideoElement | null, isVisible: boolean) => void;
  activeVideoRef: React.MutableRefObject<HTMLVideoElement | null>;
  handleVideoEnded: (postId: string | number) => void;
  handleToggleLike: (e?: any) => void;
  postLiked: boolean;
  showBurst: boolean;
  postLikeCount: number;
  setCommentSheetEntryType: (val: "caption" | "icon" | null) => void;
  currentItem: any;
  setIsCommenting: (val: boolean) => void;
  isCommenting: boolean;
  modalZIndex: number;
  zIndex?: number;
  showMentions: boolean;
  setShowMentions: (val: boolean) => void;
  isLoadingMentions: boolean;
  mentionsList: any[];
  commentText: string;
  setCommentText: React.Dispatch<React.SetStateAction<string>>;
  commentTextRef: React.MutableRefObject<string>;
  reelTextareaRef: React.RefObject<HTMLTextAreaElement | null>;
  replyingTo: any | null;
  setReplyingTo: (val: any) => void;
  handleAddComment: (text: string) => void;
  fetchMentions: () => void;
  commentPosting: boolean;
  EMOJI_SHORTCUTS: string[];
  commentsScrollRef: React.RefObject<HTMLDivElement | null>;
  handleCommentsScroll: (e: any) => void;
  comments: any[];
  formatDate: (date: any) => string;
  loadingComments: boolean;
  expandedParents: number[];
  setExpandedParents: React.Dispatch<React.SetStateAction<number[]>>;
  toggleLikeComment: (id: number) => void;
  burstingCommentId: number | null;
  hasMoreComments: boolean;
  isFetchingMore: boolean;
  commentSheetHeight: string | number;
  handleProductClick: (id: number, e?: any) => void;
  formatUrl: (url: string) => string;
  desktopTextareaRef: React.RefObject<HTMLTextAreaElement | null>;
  setShowEmojiPicker: (val: boolean) => void;

  // Desktop Standard View
  leftMediaRef: React.RefObject<HTMLDivElement | null>;
  isLargeScreen: boolean;
  post: any;
  getNoteStyles: (config: any) => any;
  mediaList: string[];
  currentMediaIndex: number;
  handleDoubleTap: (e: React.MouseEvent, options?: { disableSingleTapPause?: boolean }) => void;
  activeHeartPops: any[];
  swipeDirection: number;
  NO_IMAGE_PLACEHOLDER: string;
  isDraggingRef: React.MutableRefObject<boolean>;
  setSwipeDirection: React.Dispatch<React.SetStateAction<number>>;
  setCurrentMediaIndex: React.Dispatch<React.SetStateAction<number>>;
  firstImageAspectRatio: number | null;
  setFirstImageAspectRatio: React.Dispatch<React.SetStateAction<number | null>>;
  setViewerProfileUserId: React.Dispatch<React.SetStateAction<string | number | undefined>>;
  setFullImageUrl: React.Dispatch<React.SetStateAction<string | null>>;
  hydratedLinkedProducts: Record<string, any>;
  activePostId: string | number;
  getDiscountedPrice: (lp: any) => number;
  getDiscountInfo: (lp: any) => any;
  getPolicyText: (lp: any) => string;
  getStockCount: (lp: any) => number;
  auth: any;
  sheetTextareaRef: React.RefObject<HTMLTextAreaElement | null>;
  handleShareClick: () => void;
  commentSheetEntryType: "caption" | "icon" | null;
  isPostOwner: boolean;
  isFollowing: boolean;
  toggleFollowAuthor: () => void;
  followLoading: boolean;
  onClose: () => void;
  isPaused: boolean;
  setMenuPosition: (pos: { x: number; y: number } | null) => void;
  setLongTappedPost: (post: any) => void;
  setShowLongTapMenu: (val: boolean) => void;
  handleTimeUpdate: (id: string | number, current: number, duration: number) => void;
  showSwipeGuide: boolean;
  commentsError: string | null;
  isPreview?: boolean;
  userManualPauseRef: React.MutableRefObject<boolean>;
  computedWidth: number | null;
  computeAndSetModalWidth: (w: number, h: number) => void;
  isNavigating?: boolean;
  setIsNavigating?: React.Dispatch<React.SetStateAction<boolean>>;
  pendingTransitionRef?: React.MutableRefObject<{ showing: boolean; timer: ReturnType<typeof setTimeout> | null }>;
}
